### ISSUE TITLE
Relizensierung zu MIT

### ISSUE THREAD

**Issue by rnuske** [rnuske/et.nwfva#1]
Da es sich abzeichnet, dass das Paket et.nwfva auch in anderen Anwendungen Verwendung finden wird, scheint es günstiger  et.nwfva unter die MIT Lizenz zu stellen.

Wenn alle Autoren zugestimmt haben, werde ich et.nwfva nach MIT relizensieren.

**Comment by malbertnwfva** [comment]
Ich stimme der Relizensierung unseres Paketes et.nwfva zu MIT zu. 
Matthias

**Comment by kstaupendahl** [comment]
Ich stimme ebenfalls zu.
Kai

**Comment by rnuske** [comment]
Ich stimme auch zu und setzte es gleich um.
