### ISSUE TITLE
Hilfe-Update für et_hoehe

### ISSUE THREAD

**Issue by kstaupendahl** [rnuske/et.nwfva#2]
In diesem Passus der Hilfe zu _et_hoehe_ wird die Modellbildung der Mittelhöhen-Bonitätsfächer nicht korrekt beschrieben:

_Die Bestimmung der Bestandeshöhe über die funktionalisierten Bonitätsfächer basiert auf nichtlinearen Modellen, die durch Anpassung an die Ober- und Mittelhöhen über dem Alter bei mäßiger Durchforstung bzw. für Eichen-Oberhöhen bei starker Durchforstung aus der Ertragstafelsammlung von Schober (1995) entstanden. Für die Kiefer wurde hierbei die Chapman-Richards-Funktion (Richards 1959) und für alle anderen Baumarten die Wachstumsfunktion von Sloboda (1971) genutzt. Die Bestandeshöhen der neuen Ertragstafeln (Albert et al. 2021) sind die tabellarisierten Werte eben dieser funktionalisierten Bonitätsfächer._

Wir haben eben nicht die Mittelhöhen der Schober-ET modelliert, sondern die der Simulationsbestände. Es müsste daher heißen:

Die Ermittlung der Bestandesoberhöhe mithilfe der funktionalisierten Bonitätsfächer basiert auf nichtlinearen Modellen, die durch Anpassung an die alters- und bonitätsabhängigen Oberhöhenverläufe bei mäßiger bzw. für Eiche bei starker Durchforstung gemäß der Ertragstafelsammlung von Schober (1995) entwickelt wurden. Für die Kiefer wurde hierbei die Chapman-Richards-Funktion (Richards 1959) und für alle anderen Baumarten die Wachstumsfunktion von Sloboda (1971) genutzt, jeweils in der algebraischen Differenzenform. Die Bonitätsfächermodelle der Bestandesmittelhöhen ergaben sich durch Modellierung der Relationen der Mittel- und Oberhöhen in den den neuen ET zugrundeliegenden Simulationsbeständen (s. "Hinweise zum Geleit") und funktionalen Ausgleich der resultierenden Mittelhöhen mit den oben genannten Funktionstypen. Die Bestandesober- und -mittelhöhen der neuen Ertragstafeln (Albert et al. 2021) sind die tabellarisierten Werte eben dieser funktionalisierten Bonitätsfächer.

**Comment by rnuske** [comment]
Du bist der Experte der funktionalisierten Modelle, ich vertraue dir da und tausche die Absätze aus.
