### ISSUE TITLE
NA handling in et_hoehe() und et_bonitaet()

### ISSUE THREAD

**Issue by jan-schick** [rnuske/et.nwfva#3]
**Problem:** Wenn für `art`, `alter`, `hoehe` oder `bon` Vektoren mit `NA` übergeben werden, gibt es kryptische Fehlermeldungen. 

**Lösungsvorschläge:** Entweder bei `NA`s abbrechen oder bei `NA` Input auch `NA`s ausgeben. Ein Vorschlag für letzteres folgt als Pull-request.

**Minimalbeispiel:**
```
library(et.nwfva)

et_bonitaet(art = 211, 
            alter = c(100, 150), 
            hoehe = c(30, NA))

et_bonitaet(art = 211, 
            alter = c(NA, 100), 
            hoehe = c(30, 35))

et_hoehe(art = 211, 
         alter = c(100, 100), 
         bon = c(1, NA))

et_hoehe(art = 211, 
         alter = c(NA, 100), 
         bon = c(1, 2))
```

**Comment by rnuske** [comment]
Herzlichen Dank fürs Finden und Fixen!

Vermutlich sollte man das auch noch für et_bontrans() und et_tafel() nachziehen. et_tafel() könnte nervig sein, weil es so viele verschiedene Wege gibt es zu nutzen. Mal sehen, ob ich demnächst dazu komme.
