### ISSUE TITLE
Alterbestimmung über Baumart, Höhe und Bonität

### ISSUE THREAD

**Issue by wiesehahn** [rnuske/et.nwfva#5]
Aktuell ist über die Funktionen 
`et_bonitaet()` implementiert dass über *Art*, *Höhe* und *Alter* die **Bonität**,
und mit `et_hoehe()` über *Art*, *Bonität* und *Alter* die **Höhe** bestimmt wird. 

Die dritte Möglichkeit nach der ich gerade suche wäre über *Art*, *Höhe* und *Bonität* das **Alter** zu schätzen, also quasi `et_alter()`. 
Ich weiß nicht ob das wirklich sinnvoll ist aber theoretisch müsste das über den Dreisatz doch genauso funktionieren.
Ist das bereits irgendwie möglich?

**Comment by rnuske** [comment]
Moin moin Jens,
bitte entschuldige die lange Wartezeit.
Die von in dir gewünschte Funktionalität ist eher untypisch für Ertragstafelanwendungen. Ich würde sie aber aufnehmen, wenn Du sie implementieren möchtest ;-) Die traditionelle Variante könnte vermutlich in Anlehnung an et_hoehe umgesetzt werden. Wege einer funktionalisierten Variante müsstest Du mal bei Matthias A. oder Kai S. nachfragen.
gruss robert

**Comment by wiesehahn** [comment]
Hey Robert, danke für die Antwort, 
ja genau, bin mir auch immer noch nicht ganz sicher wie funktional das ist, aber meine Theroie ist, dass es untypisch ist weil man halt immer von den Bodenmesswerten ausgeht.
Bei flächendeckenden Anwendungen sieht das eher anders aus, da kann ich Höhe, Art und Standort einigermaßen über Fernerkundungsdaten / Geodaten schätzen das Alter aber nicht. 
Brauche ich aber nicht dringend, hatte mich erstmal bloß gewundert ob das schon implementiert ist.

**Comment by rnuske** [comment]
Ich schließe den jetzt erstmal, da ich die Funktion in naher Zukunft nicht implementieren werde.

Einen Pull Request dazu würde ich aber annehmen ;-)
